apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  mykey: cGFzc3dvcmRvcnNvbWV0aGluZw==
---
apiVersion: k8s-rds.io/v1
kind: Database
metadata:
  name: mypgsql
  namespace: default
spec:
  class: db.t2.medium
  engine: postgres
  dbname: thepgsql
  name: thatpgsql
  deleteprotection: false
  password:
    key: mykey
    name: mysecret
  username: postgres
  size: 10
  tags: "environment=test,team=backend"
  skipfinalsnapshot: false
