apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-rds
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-rds
  template:
    metadata:
      labels:
        name: k8s-rds
    spec:
      containers:
      - image: sorenmat/k8s-rds:latest
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: k8s-rds
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: k8s-rds
        imagePullPolicy: Always
        name: k8s-rds
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: k8s-rds-operator
