name: CI

on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-multi-arch:
    uses: tradeshift/actions-workflow-multiarch/.github/workflows/docker-multiarch.yml@master
    with:
      registry: eu.gcr.io/tradeshift-base/k8s-rds
      tags: pr
    secrets:
      eu-key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_NOBASE64 }}
